//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloor.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class master_floorEntities : DbContext
    {
        public master_floorEntities()
            : base("name=master_floorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<materials> materials { get; set; }
        public virtual DbSet<materials_types> materials_types { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<partners> partners { get; set; }
        public virtual DbSet<partners_types> partners_types { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<products_materials> products_materials { get; set; }
        public virtual DbSet<products_types> products_types { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
