//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public long id { get; set; }
        public long product { get; set; }
        public long partner { get; set; }
        public int qunatity { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual partners partners { get; set; }
        public virtual products products { get; set; }
    }
}
