//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloor.Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public partners()
        {
            this.orders = new HashSet<orders>();
        }
    
        public long id { get; set; }
        public long type { get; set; }
        public string title { get; set; }
        public string director { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string legal_address { get; set; }
        public long inn { get; set; }
        public Nullable<int> rating { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders> orders { get; set; }
        public virtual partners_types partners_types { get; set; }

        public string Discount
        {
            get
            {
                using (var context = new master_floorEntities())
                {
                    var partnerOrders = context.orders.Where(o => o.partner == this.id);

                    double sum = 0;

                    foreach (var order in partnerOrders)
                    {
                        sum += double.Parse(order.qunatity.ToString());
                    }

                    if (sum >= 10000 && sum < 50000) return "5%";
                    else if (sum >= 50000 && sum < 300000) return "10%";
                    else if (sum > 300000) return "15%";
                    else return "0%";
                }
            }
        }
    }
}
