//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_materials
    {
        public long product { get; set; }
        public long material { get; set; }
        public Nullable<decimal> quantity { get; set; }
    
        public virtual materials materials { get; set; }
        public virtual products products { get; set; }
    }
}
